version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    volumes:
      - .:/myapp
      - /myapp/tmp # Airの一時ファイル用
    working_dir: /myapp
    ports:
      - "8080:8080" # アプリケーションのポート
    command: >
      sh -c "
        go run github.com/air-verse/air@latest -c .air.toml
      "
#      sh -c "
#        go run ./cmd/main.go
#      "